# syntax=docker/dockerfile:1
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env
WORKDIR /app
EXPOSE 7124
EXPOSE 80
EXPOSE 443



COPY *.csproj ./
RUN dotnet restore
COPY ./ ./
RUN dotnet publish PE2023test.sln -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet", "PE2023test.dll","--urls", "http://*:7124"]